version: '3'

services:
  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    environment:
      - DATABASE_URL=sqlite3:///rails/storage/development.sqlite3
