---
openapi: 3.0.3
info:
  title: Real Estate Management API V1
  version: v1
servers:
- url: http://localhost:3000/api/v1
  description: Local development server
paths:
  "/properties":
    get:
      summary: Retrieves a list of properties
      tags:
      - Properties
      responses:
        '200':
          description: List of properties
    post:
      summary: Creates a property
      tags:
      - Properties
      parameters: []
      responses:
        '201':
          description: Property created
        '422':
          description: Property not created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                location:
                  type: string
                price:
                  type: number
                status:
                  type: string
              required:
              - name
              - location
              - price
              - status
  "/properties/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves a specific property by ID
      tags:
      - Properties
      responses:
        '200':
          description: Property found
        '404':
          description: Property not found
    put:
      summary: Updates a property by ID
      tags:
      - Properties
      parameters: []
      responses:
        '200':
          description: Property updated
        '404':
          description: Property not found
        '422':
          description: Property not updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                location:
                  type: string
                price:
                  type: number
                status:
                  type: string
              required: []
    delete:
      summary: Deletes a property by ID
      tags:
      - Properties
      responses:
        '204':
          description: Property deleted
        '404':
          description: Property not found
        '422':
          description: Property not deleted
  "/property_assignments":
    post:
      summary: Assign a property to an agent
      tags:
      - Property Assignments
      parameters:
      - name: property_id
        in: query
        required: true
        schema:
          type: integer
      - name: agent_id
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Property assigned successfully
        '404':
          description: Property not found
        '422':
          description: Property status is Sold
